**연습 문제 4-1**

In [6]:
import numpy as np

A = np.arange(12).reshape(3,4)

a = int(input('Enter the row index(0~2):'))
b = int(input('Enter the column index(0~3):'))

print(f'The matrix element at index ({a},{b}) is {A[a,b]}')

Enter the row index(0~2):0
Enter the column index(0~3):2
The matrix element at index (0,2) is 2


In [2]:
# 정답

# indexing

A = np.arange(12).reshape(3,4)
print(A)

# find the element in the 2nd row, 4th column
ri = 1
ci = 3

print(f'The matrix element at index ({ri+1},{ci+1}) is {A[ri,ci]}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The matrix element at index (2,4) is 7


**연습 문제 4-2**

In [7]:
C = np.arange(100).reshape(10,10)
C_1 = C[0:5:1,0:5:1]

print(C)
print(C_1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [8]:
# 정답

# Create the matrix
C = np.arange(100).reshape((10,10))

# extract submatrix
C_1 = C[0:5:1,0:5:1]

# here's what the matrices look like
print(C), print(' ')
print(C_1)



# visualize the matrices as maps
_,axs = plt.subplots(1,2,figsize=(10,5))

axs[0].imshow(C,cmap='gray',origin='upper',vmin=0,vmax=np.max(C))
axs[0].plot([4.5,4.5],[-.5,9.5],'w--')
axs[0].plot([-.5,9.5],[4.5,4.5],'w--')
axs[0].set_title('Original matrix')
# text labels
for (j,i),num in np.ndenumerate(C):
  axs[0].text(i,j,num,color=[.8,.8,.8],ha='center',va='center')


axs[1].imshow(C_1,cmap='gray',origin='upper',vmin=0,vmax=np.max(C))
axs[1].set_title('Submatrix')
# text labels
for (j,i),num in np.ndenumerate(C_1):
  axs[1].text(i,j,num,color=[.8,.8,.8],ha='center',va='center')


plt.savefig('Figure_04_06.png',dpi=300)
plt.show()

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
 
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


NameError: name 'plt' is not defined

**연습 문제 4-6**

In [ ]:
m = np.random.randint(0,)
n = np.random.randint(0,)
A = np.random.randn(m,n)
B = np.random.randn(n,m)

C = np.zeros(m,m)
for i_row in range(m):
    for i_col in range(m):
        C[i_row,i_col] = np.dot(A[i_row,:],B[:,i_col]) # C의 특정 위치에 내적값을 저장

In [ ]:
# 정답

# generate two matrices
m = 4
n = 6
A = np.random.randn(m,n);
B = np.random.randn(n,m)

# build up the product matrix element-wise
C1 = np.zeros((m,m))
for rowi in range(m):
  for coli in range(m):
    C1[rowi,coli] = np.dot( A[rowi,:],B[:,coli] )



# implement matrix multiplication directly
C2 = A@B

# compare the results (using isclose(); results should be a matrix of TRUEs)
np.isclose( C1,C2 )

**연습 문제 4-8**

In [9]:
def symmetric_matrix_TF(A):
    if A == A.T:
        return True
    else:
        return False

In [10]:
# 정답

def isMatrixSymmetric(S):

  # difference between matrix and its transpose
  D = S-S.T

  # check whether sum of squared errors (SSE) is smaller than a threshold
  sse = np.sum(D**2)

  # output TRUE if sse is tiny; FALSE means the matrix is asymmetric
  return sse<10**-15

# note: There are many other ways you could solve this.
# If you want to explore different methods, consider np.all() or np.isclose()

**연습 문제 4-9**

In [12]:
A = np.random.randn(3,3) # 정방이면서 비대칭 (대칭일 수도 있겠지만..)
A_mean = (A + A.T) / 2
print(A_mean)

[[-0.83458099  0.32050139 -0.43444949]
 [ 0.32050139  0.13161207 -0.14438772]
 [-0.43444949 -0.14438772  0.62120265]]


In [13]:
# 정답

# create symmetric and nonsymmetric matrices
A = np.random.randn(4,4)
AtA = (A + A.T) / 2 # additive method!

# test!
print(isMatrixSymmetric(A))
print(isMatrixSymmetric(AtA))

False
True
