**연습 문제 8-1**

In [2]:
import numpy as np

Q  = np.linalg.qr(np.random.randn(5,5))[0]
Q_t = Q.T
Q_i = np.linalg.inv(Q)

print(np.round(Q_t @ Q,10))
print(np.round(Q @ Q_t,10))
print(np.round(Q_i @ Q,10))
print(np.round(Q @ Q_i,10))

[[ 1.  0. -0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1.  0. -0.]
 [ 0.  0.  0.  1. -0.]
 [ 0.  0. -0. -0.  1.]]
[[ 1. -0.  0.  0. -0.]
 [-0.  1.  0. -0. -0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -0.  0.  1.  0.]
 [-0. -0.  0.  0.  1.]]
[[ 1.  0.  0. -0.  0.]
 [-0.  1. -0.  0. -0.]
 [-0.  0.  1.  0.  0.]
 [ 0.  0. -0.  1. -0.]
 [ 0.  0. -0.  0.  1.]]
[[ 1. -0.  0. -0.  0.]
 [-0.  1.  0. -0.  0.]
 [-0.  0.  1.  0. -0.]
 [-0.  0. -0.  1. -0.]
 [ 0. -0.  0. -0.  1.]]


In [ ]:
# 정답

# compute matrices
Q  = np.linalg.qr( np.random.randn(5,5) )[0]
Qt = Q.T
Qi = np.linalg.inv( Q )

# QtQ
print(np.round( Qt@Q,8 )), print(' ')

# QQt
print(np.round( Q@Qt,8 )), print(' ')

# Q^-1 Q
print(np.round( Qi@Q,8 )), print(' ')

# QQ^-1
print(np.round( Q@Qi,8 ))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0.  0.]
 [ 0. -0.  0.  1.  0.]
 [ 0. -0.  0.  0.  1.]]
 
[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0.  0. -0.]
 [ 0. -0.  1. -0. -0.]
 [ 0.  0. -0.  1.  0.]
 [ 0. -0. -0.  0.  1.]]
 
[[ 1. -0.  0.  0.  0.]
 [ 0.  1.  0. -0.  0.]
 [-0. -0.  1.  0. -0.]
 [-0. -0.  0.  1.  0.]
 [-0.  0.  0. -0.  1.]]
 
[[ 1. -0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0. -0.]
 [ 0.  0. -0.  1. -0.]
 [ 0. -0.  0.  0.  1.]]


**연습 문제 8-2**

In [ ]:
A = np.random.randn(4,4)

def GS(A):
    Q = np.zeros((A.shape[0],A.shape[1]))

    for i in range(A.shape[1]):
        Q[:,i] = A[:,i]

        a = A[:,i]
        for j in range(i):
            q = Q[:,j]
            Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q # 직교화

In [ ]:
# 정답

# create the matrix
m = 4
n = 4
A = np.random.randn(m,n)

# initialize
Q = np.zeros((m,n))


# the GS algo
for i in range(n):

    # initialize
    Q[:,i] = A[:,i]

    # orthogonalize
    a = A[:,i] # convenience
    for j in range(i): # only to earlier cols
        q = Q[:,j] # convenience
        Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q

    # normalize
    Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i])


# "real" QR decomposition for comparison
Q2,R = np.linalg.qr(A)


# note the possible sign differences.
# seemingly non-zero columns will be 0 when adding
print( np.round( Q-Q2 ,10) ), print(' ')
print( np.round( Q+Q2 ,10) )

**연습 문제 8-3**

In [5]:
U = np.linalg.qr(np.random.randn(6,6))[0]

# 1
Q,R = np.linalg.qr(U)
print(np.round(R,3))
print(' ')

# 2
for i in range(U.shape[0]):
  U[:,i] = U[:,i]*(10+i)

Q,R = np.linalg.qr(U)
print(np.round(R,3))
print(' ')

print(np.round(Q.T @ Q,4))
print(' ')

# 3
U[0,3] = 0

Q,R = np.linalg.qr(U)
print(np.round(R,3))
print(' ')

[[ 1.  0.  0.  0. -0. -0.]
 [ 0.  1. -0.  0.  0. -0.]
 [ 0.  0.  1. -0.  0.  0.]
 [ 0.  0.  0.  1.  0. -0.]
 [ 0.  0.  0.  0.  1. -0.]
 [ 0.  0.  0.  0.  0.  1.]]
 
[[10.  0. -0.  0. -0.  0.]
 [ 0. 11. -0. -0.  0. -0.]
 [ 0.  0. 12.  0.  0. -0.]
 [ 0.  0.  0. 13.  0. -0.]
 [ 0.  0.  0.  0. 14.  0.]
 [ 0.  0.  0.  0.  0. 15.]]
 
[[ 1.  0. -0. -0.  0.  0.]
 [ 0.  1. -0.  0. -0.  0.]
 [-0. -0.  1.  0.  0.  0.]
 [-0.  0.  0.  1. -0. -0.]
 [ 0. -0.  0. -0.  1. -0.]
 [ 0.  0.  0. -0. -0.  1.]]
 
[[10.     0.    -0.     3.889 -0.     0.   ]
 [ 0.    11.    -0.     1.198  0.    -0.   ]
 [ 0.     0.    12.    -1.739  0.    -0.   ]
 [ 0.     0.     0.    10.874  2.511  1.963]
 [ 0.     0.     0.     0.    13.773 -0.358]
 [ 0.     0.     0.     0.     0.    14.867]]
 


In [6]:
# 정답

# create an orthogonal matrix, call it U (to avoid confusing with Q)
U = np.linalg.qr( np.random.randn(6,6) )[0]


# part 2: modulate the column norms
for i in range(U.shape[0]):
  U[:,i] = U[:,i]*(10+i)


# part 3: Change one matrix element
U[0,3] = 0 # this is q_{1,4}


# QR decomp
q,r = np.linalg.qr(U)

# show R and, for part 2, Q'Q
print( np.round(r,3) ), print(' ')
# print( np.round(Q.T@Q,4))

[[ 1.0000e+01 -0.0000e+00 -0.0000e+00  1.3940e+00  0.0000e+00 -0.0000e+00]
 [ 0.0000e+00  1.1000e+01 -0.0000e+00  5.4200e-01 -0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.2000e+01  1.1700e-01  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  1.2822e+01 -2.6300e-01  1.4500e-01]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.3998e+01  3.0000e-03]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.4999e+01]]
 


(None, None)

**연습 문제 8-6**

In [14]:
# 1

M = 6
N = 6

Q = np.linalg.qr(np.random.randn(M,N))[0]

print(np.round(np.linalg.norm(Q,2),3))
print(np.round(np.linalg.norm(Q,'fro') / np.sqrt(M),3))

# 2

v = np.random.randn(M,1)

v_norm  = np.linalg.norm(v)
Qv_norm = np.linalg.norm(Q @ v)

print(v_norm)
print(Qv_norm)

1.0
1.0
3.043257177480095
3.043257177480095


In [ ]:
# 정답

# create a random orthogonal matrix
n = 13
Q,R = np.linalg.qr(np.random.randn(n,n))

# print out the norms
print( np.linalg.norm(Q,2),               # induced 2-norm
       np.sqrt( np.sum(Q**2) )/np.sqrt(n) # manually computed Frobenius norm
)

# effects of matrix multiplication on vector norm

# a random vector
v = np.random.randn(n,1)

# norms
norm_v  = np.linalg.norm(v)
norm_Qv = np.linalg.norm(Q@v)

# print them
print(norm_v)
print(norm_Qv)

**연습 문제 8-7**

In [17]:
A = np.random.randn(10,4)

R = np.linalg.qr(A,'complete')[1]

# 처음 N개의 행을 구성하는 행렬의 완전 역행렬
R_sub = R[:4,:]
R_sub_inv = np.linalg.inv(R_sub)

# 높은 행렬 그대로의 의사역행렬
R_left_inv = np.linalg.pinv(R)
R_left_inv_sub = R_left_inv[:,:4]

print(np.round(R_sub_inv,3))
print(np.round(R_left_inv_sub,3))

[[ 0.309  0.022 -0.137 -0.245]
 [ 0.     0.343 -0.293 -0.181]
 [ 0.     0.     0.409  0.223]
 [ 0.     0.     0.     0.311]]
[[ 0.309  0.022 -0.137 -0.245]
 [-0.     0.343 -0.293 -0.181]
 [-0.    -0.     0.409  0.223]
 [-0.     0.    -0.     0.311]]


In [18]:
# 정답

# the matrix
A = np.random.randn(10,4)

# get R
_,R = np.linalg.qr(A,'complete')

# examine R
np.round(R,3)

# invertible submatrix
Rsub = R[:4,:]

# inverses
Rsub_inv = np.linalg.inv(Rsub)
Rleftinv = np.linalg.pinv(R)

# print out both
print('Full inverse of R submatrix:')
print(np.round(Rsub_inv,3)), print(f'\n\n')

print('Left inverse of R:')
print(np.round(Rleftinv,3))

Full inverse of R submatrix:
[[-0.28  -0.191 -0.209 -0.196]
 [ 0.     0.607  0.121  0.142]
 [ 0.     0.     0.402  0.103]
 [-0.    -0.    -0.    -0.422]]



Left inverse of R:
[[-0.28  -0.191 -0.209 -0.196  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.607  0.121  0.142  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.402  0.103  0.     0.     0.     0.     0.     0.   ]
 [-0.    -0.     0.    -0.422  0.     0.     0.     0.     0.     0.   ]]
