### 솔루션 링크

In [2]:
#  https://github.com/Sancho-kim/LinAlg4DS

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### [연습문제 8-1]


In [3]:

# compute matrices
Q  = np.linalg.qr( np.random.randn(5,5) )[0]
Qt = Q.T
Qi = np.linalg.inv( Q )

# QtQ
print(np.round( Qt@Q,8 )), print(' ')

# QQt
print(np.round( Q@Qt,8 )), print(' ')

# Q^-1 Q
print(np.round( Qi@Q,8 )), print(' ')

# QQ^-1
print(np.round( Q@Qi,8 ))

[[ 1.  0.  0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [ 0.  0.  1. -0.  0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0.  0. -0.  1.]]
 
[[ 1.  0.  0.  0. -0.]
 [ 0.  1. -0.  0.  0.]
 [ 0. -0.  1.  0. -0.]
 [ 0.  0.  0.  1. -0.]
 [-0.  0. -0. -0.  1.]]
 
[[ 1. -0.  0. -0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0. -0.  1. -0. -0.]
 [-0. -0.  0.  1. -0.]
 [ 0.  0.  0. -0.  1.]]
 
[[ 1.  0.  0. -0.  0.]
 [-0.  1. -0. -0.  0.]
 [-0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


### [연습문제 8-2]

In [4]:
# create the matrix
m = 4
n = 4
A = np.random.randn(m,n)

# initialize
Q = np.zeros((m,n))


# the GS algo
for i in range(n):

    # initialize
    Q[:,i] = A[:,i]

    # orthogonalize
    a = A[:,i] # convenience
    for j in range(i): # only to earlier cols
        q = Q[:,j] # convenience
        Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q

    # normalize
    Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i])


# "real" QR decomposition for comparison
Q2,R = np.linalg.qr(A)


# note the possible sign differences.
# seemingly non-zero columns will be 0 when adding
print( np.round( Q-Q2 ,10) ), print(' ')
print( np.round( Q+Q2 ,10) )

[[ 1.87934437  0.11191023  0.         -0.        ]
 [-0.00378086  1.31803917  0.          0.        ]
 [-0.6011362  -0.43797911 -0.          0.        ]
 [ 0.32662781 -1.43472058  0.          0.        ]]
 
[[ 0.         -0.          0.12808759 -0.66267219]
 [ 0.          0.         -1.5021974  -0.07849477]
 [-0.          0.         -0.28692739 -1.8342525 ]
 [ 0.         -0.         -1.28244658  0.43614436]]


### [연습문제 8-3]

In [5]:
# create an orthogonal matrix, call it U (to avoid confusing with Q)
U = np.linalg.qr( np.random.randn(6,6) )[0]


# part 2: modulate the column norms
for i in range(U.shape[0]):
  U[:,i] = U[:,i]*(10+i)


# part 3: Change one matrix element
U[0,3] = 0 # this is q_{1,4}


# QR decomp
q,r = np.linalg.qr(U)

# show R and, for part 2, Q'Q
print( np.round(r,3) ), print(' ')
# print( np.round(Q.T@Q,4))

[[ 1.0000e+01 -0.0000e+00  0.0000e+00  4.3400e-01  0.0000e+00 -0.0000e+00]
 [ 0.0000e+00  1.1000e+01  0.0000e+00  5.1500e-01 -0.0000e+00 -0.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.2000e+01 -5.4300e-01 -0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  1.2938e+01 -1.5900e-01  3.4700e-01]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.3999e+01  4.0000e-03]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.4996e+01]]
 


(None, None)

### [연습문제 8-6]

In [6]:
# create a random orthogonal matrix
n = 13
Q,R = np.linalg.qr(np.random.randn(n,n))

# print out the norms
print( np.linalg.norm(Q,2),               # induced 2-norm
       np.sqrt( np.sum(Q**2) )/np.sqrt(n) # manually computed Frobenius norm
)


# effects of matrix multiplication on vector norm

# a random vector
v = np.random.randn(n,1)

# norms
norm_v  = np.linalg.norm(v)
norm_Qv = np.linalg.norm(Q@v)

# print them
print(norm_v)
print(norm_Qv)


1.0000000000000002 1.0
2.5732715207034516
2.5732715207034516


### [연습문제 8-7]

In [7]:
# the matrix
A = np.random.randn(10,4)

# get R
_,R = np.linalg.qr(A,'complete')

# examine R
np.round(R,3)


# invertible submatrix
Rsub = R[:4,:]

# inverses
Rsub_inv = np.linalg.inv(Rsub)
Rleftinv = np.linalg.pinv(R)

# print out both
print('Full inverse of R submatrix:')
print(np.round(Rsub_inv,3)), print(f'\n\n')

print('Left inverse of R:')
print(np.round(Rleftinv,3))

Full inverse of R submatrix:
[[ 0.409  0.003 -0.084 -0.188]
 [ 0.     0.288 -0.043  0.108]
 [-0.    -0.    -0.354 -0.538]
 [-0.    -0.    -0.    -0.478]]



Left inverse of R:
[[ 0.409  0.003 -0.084 -0.188  0.     0.     0.     0.     0.     0.   ]
 [-0.     0.288 -0.043  0.108  0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.    -0.354 -0.538  0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.     0.    -0.478  0.     0.     0.     0.     0.     0.   ]]
