<a href="https://colab.research.google.com/github/Hyubbbb/EPOCH_LinearAlgebra/blob/main/h_Jiyun/Chapter4_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## 연습 문제 4-1

In [ ]:
A = np.arange(12).reshape(3,4)
print("The matrix element at index (2,4) is",A[1,3])

The matrix element at index (2,4) is 7


## 연습 문제 4-2

In [ ]:
C = np.arange(100).reshape(10,10)
C1 = C[0:5:1, 0:5:1] # C의 부분 행렬

print(C)
print(C1)

# import plotly.graph_objects as go

# 시각화..?
# fig = go.Figure()
# fig.add_trace(go.Table(cells=dict(values= C)))
# fig.show()

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


## 연습 문제 4-6

### 행렬 생성

In [ ]:
A = np.arange(50).reshape(10,5)
B = np.arange(50).reshape(5,10)

 ### for 루프를 사용한 행렬 곱셈

In [ ]:
z = np.array([[sum([A[i][k]*B[k][j] for k in range(5)])
for j in range(10)] for i in range(10)])
print(z.reshape(10,10))

[[ 300  310  320  330  340  350  360  370  380  390]
 [ 800  835  870  905  940  975 1010 1045 1080 1115]
 [1300 1360 1420 1480 1540 1600 1660 1720 1780 1840]
 [1800 1885 1970 2055 2140 2225 2310 2395 2480 2565]
 [2300 2410 2520 2630 2740 2850 2960 3070 3180 3290]
 [2800 2935 3070 3205 3340 3475 3610 3745 3880 4015]
 [3300 3460 3620 3780 3940 4100 4260 4420 4580 4740]
 [3800 3985 4170 4355 4540 4725 4910 5095 5280 5465]
 [4300 4510 4720 4930 5140 5350 5560 5770 5980 6190]
 [4800 5035 5270 5505 5740 5975 6210 6445 6680 6915]]


### Numpy @ 연산자

In [ ]:
print(A@B)
# print(np.dot(A,B)) 내적이 왜 스칼라가 아니라 행렬이 출력되지?

[[ 300  310  320  330  340  350  360  370  380  390]
 [ 800  835  870  905  940  975 1010 1045 1080 1115]
 [1300 1360 1420 1480 1540 1600 1660 1720 1780 1840]
 [1800 1885 1970 2055 2140 2225 2310 2395 2480 2565]
 [2300 2410 2520 2630 2740 2850 2960 3070 3180 3290]
 [2800 2935 3070 3205 3340 3475 3610 3745 3880 4015]
 [3300 3460 3620 3780 3940 4100 4260 4420 4580 4740]
 [3800 3985 4170 4355 4540 4725 4910 5095 5280 5465]
 [4300 4510 4720 4930 5140 5350 5560 5770 5980 6190]
 [4800 5035 5270 5505 5740 5975 6210 6445 6680 6915]]


## 연습 문제 4-8

### 대칭 행렬과 비대칭 행렬 생성

In [ ]:
# 대칭 행렬
A = np.random.random((3,3))
print(A)

# 비대칭 행렬
B = np.array([[1, 2, 3],
             [2, 4, 5],
            [3, 5, 6]])
print(B)


[[0.25242109 0.69776235 0.03822278]
 [0.02470377 0.23252879 0.80310727]
 [0.27990424 0.87139817 0.43706158]]
[[1 2 3]
 [2 4 5]
 [3 5 6]]


### 행렬의 대칭 여부

In [ ]:
print(np.allclose(A, A.T))
print(np.allclose(B, B.T))

False
True


## 연습 문제 4-9

In [ ]:
# 비대칭 행렬
A = np.random.random((3,3))
print(A)

# 전치로 평균화
B = (A + A.T)/2
print(B)

print(np.allclose(B, B.T))

[[0.01249836 0.84096493 0.40810662]
 [0.78503463 0.260971   0.70596375]
 [0.66790125 0.16583348 0.37968921]]
[[0.01249836 0.81299978 0.53800393]
 [0.81299978 0.260971   0.43589862]
 [0.53800393 0.43589862 0.37968921]]
True
