<a href="https://colab.research.google.com/github/Hyubbbb/EPOCH_LinearAlgebra/blob/main/h_Jiyun/Chapter8_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 연습 문제 8-1

### Square Matrix Q

In [17]:
Q, R = np.linalg.qr(np.random.rand(6,6), 'complete')
QT = Q.T
Q_inv = np.linalg.inv(Q)

array([[-0.31365824, -0.58585668, -0.34915625, -0.47005738, -0.31123229,
        -0.34447191],
       [ 0.58142965, -0.02932244, -0.51139267, -0.21476737, -0.23642039,
         0.54547014],
       [-0.54852933,  0.11641226, -0.62666454,  0.49216456,  0.0507533 ,
         0.21921101],
       [ 0.2769137 ,  0.54148824, -0.40825556, -0.03286348, -0.03939702,
        -0.67882586],
       [-0.32216697,  0.48739977,  0.21884869, -0.19924744, -0.73441449,
         0.17801961],
       [-0.28670699,  0.3340543 , -0.09639325, -0.67075743,  0.55113265,
         0.2079722 ]])

### Check Identity Matrix

In [18]:
QT@Q

array([[ 1.00000000e+00,  8.12226261e-17, -1.55894737e-16,
         9.09643450e-18, -5.19746347e-17, -1.30576852e-16],
       [ 8.12226261e-17,  1.00000000e+00, -3.26397375e-17,
        -9.11599047e-17, -1.08403126e-16, -7.63667591e-17],
       [-1.55894737e-16, -3.26397375e-17,  1.00000000e+00,
        -1.49157915e-16, -7.52773285e-18, -1.27207062e-16],
       [ 9.09643450e-18, -9.11599047e-17, -1.49157915e-16,
         1.00000000e+00,  1.26751115e-17,  3.77831014e-17],
       [-5.19746347e-17, -1.08403126e-16, -7.52773285e-18,
         1.26751115e-17,  1.00000000e+00, -1.70028856e-17],
       [-1.30576852e-16, -7.63667591e-17, -1.27207062e-16,
         3.77831014e-17, -1.70028856e-17,  1.00000000e+00]])

In [19]:
Q@Q.T

array([[ 1.00000000e+00, -1.34906970e-16, -3.76622455e-16,
        -2.12511030e-17, -1.94751633e-17,  8.64104427e-17],
       [-1.34906970e-16,  1.00000000e+00,  1.72459195e-16,
        -8.21012998e-17,  3.75244393e-17, -7.83818061e-17],
       [-3.76622455e-16,  1.72459195e-16,  1.00000000e+00,
         5.98120267e-17, -5.35868077e-17, -8.55872436e-17],
       [-2.12511030e-17, -8.21012998e-17,  5.98120267e-17,
         1.00000000e+00, -1.07949689e-16,  1.37769247e-17],
       [-1.94751633e-17,  3.75244393e-17, -5.35868077e-17,
        -1.07949689e-16,  1.00000000e+00, -6.99501470e-18],
       [ 8.64104427e-17, -7.83818061e-17, -8.55872436e-17,
         1.37769247e-17, -6.99501470e-18,  1.00000000e+00]])

In [20]:
Q_inv@Q

array([[ 1.00000000e+00, -8.78349273e-17, -1.52993830e-18,
        -8.73231158e-18,  2.83489126e-17, -5.88549008e-17],
       [ 1.89328766e-17,  1.00000000e+00, -8.13143589e-17,
         1.70592018e-16, -6.46646927e-17, -2.54013484e-17],
       [-9.08225694e-17,  1.18753879e-16,  1.00000000e+00,
         1.19483468e-16, -1.94076635e-17,  6.82484735e-17],
       [ 3.68520101e-17, -3.56487535e-17, -1.03800369e-17,
         1.00000000e+00, -1.50804641e-17, -1.77280498e-17],
       [ 5.21087739e-17, -2.51363988e-17,  1.32889489e-17,
        -1.20267627e-18,  1.00000000e+00, -1.00639917e-17],
       [-5.67676142e-18,  2.07777555e-17, -3.00625471e-17,
         1.00275258e-17,  1.14836099e-16,  1.00000000e+00]])

In [21]:
Q@Q_inv

array([[ 1.00000000e+00, -4.75649485e-17, -6.97828877e-17,
        -5.30819731e-17,  2.05062957e-17, -2.46118597e-17],
       [ 3.87090824e-18,  1.00000000e+00, -1.04316926e-18,
        -1.72582465e-17, -1.82268426e-17, -5.06262305e-17],
       [-1.51108403e-16, -7.35780793e-17,  1.00000000e+00,
         3.52324384e-17, -6.64724593e-19,  8.09462101e-17],
       [ 6.50447259e-18,  2.01233103e-17, -3.71621756e-17,
         1.00000000e+00,  1.15457414e-16,  6.92880759e-17],
       [ 3.60359879e-17,  3.18475744e-17,  6.91844582e-17,
         8.74947791e-18,  1.00000000e+00,  6.23939243e-17],
       [ 1.90493851e-16,  6.50620956e-17, -1.04654166e-16,
        -4.64002502e-17,  2.08808440e-17,  1.00000000e+00]])

## 연습 문제 8-2

### GS process

In [142]:
V = np.random.rand(4,4)
x1 = V[:,0]
x2 = V[:,1]
x3 = V[:,2]
x4 = V[:,3]

v1 = x1
v2 = x2 - ((x2@v1)/(v1@v1))*v1
v3 = x3 - ((x3@v1)/(v1@v1))*v1 - ((x3@v2)/(v2@v2))*v2
v4 = x4 - ((x4@v1)/(v1@v1))*v1 - ((x4@v2)/(v2@v2))*v2 -((x4@v3)/(v3@v3))*v3

VQ = np.zeros((4,4))
VQ[:,0] = v1/np.linalg.norm(v1)
VQ[:,1] = v2/np.linalg.norm(v2)
VQ[:,2] = v3/np.linalg.norm(v3)
VQ[:,3] = v4/np.linalg.norm(v4)

print(VQ)

Q,R = np.linalg.qr(V)
print('')
print(Q)

[[ 0.39751489 -0.30294254 -0.07093604 -0.86323566]
 [ 0.56465848 -0.66328296  0.03991067  0.48951369]
 [ 0.7031735   0.66537014 -0.22578686  0.10885723]
 [ 0.16938046  0.15988779  0.97077057 -0.05788474]]

[[-0.39751489 -0.30294254 -0.07093604 -0.86323566]
 [-0.56465848 -0.66328296  0.03991067  0.48951369]
 [-0.7031735   0.66537014 -0.22578686  0.10885723]
 [-0.16938046  0.15988779  0.97077057 -0.05788474]]


## 연습 문제 8-3

### Orthogonal Matrix 'U'

In [67]:
U,R1 = np.linalg.qr(np.random.rand(6,6), 'complete')
Q,R = np.linalg.qr(U, 'complete')
R

array([[ 1.00000000e+00,  2.77555756e-16, -3.33066907e-16,
        -4.44089210e-16, -5.55111512e-17, -3.33066907e-16],
       [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16,
         2.22044605e-16,  3.64291930e-17,  2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -2.22044605e-16, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  8.32667268e-17, -5.55111512e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

### norm 값 수정

각 열에 10 ~ 15를 곱해줌으로써 norm값을 10 ~ 15로 수정

In [68]:
for i in range(6):
  U[:,i] = U[:,i]*(10+i)
print(U)

[[-3.26223352  2.81287214 -6.62441679 -6.63375179 -4.89255587 -5.63095594]
 [-6.88666459 -5.48422252  3.50002138  3.04391244 -2.41033495 -4.92114347]
 [-0.49273064  1.41800287 -3.741353    7.61676876 -8.81858287  5.68598269]
 [-4.60543239  1.24289517  2.99876048 -5.61420983 -0.42127601 10.87137039]
 [-2.32244631  8.90556527  4.70584024  3.37524042  1.12304787 -3.76456671]
 [-3.88395874  0.38267525 -6.53695138  3.8472286   9.32990186  2.0941887 ]]


In [69]:
Q,R = np.linalg.qr(U, 'complete')
print(R)
print(Q@Q.T)

# R은 대각선 원소가 10에서 15인 대각 행렬
# Q@Q.T는 Identity Matrix

[[ 1.00000000e+01  2.22044605e-15 -3.55271368e-15 -4.44089210e-15
  -2.66453526e-15 -2.66453526e-15]
 [ 0.00000000e+00  1.10000000e+01  4.44089210e-15  4.44089210e-15
   8.04911693e-16 -6.66133815e-16]
 [ 0.00000000e+00  0.00000000e+00  1.20000000e+01 -3.55271368e-15
  -3.55271368e-15  8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.30000000e+01
   2.22044605e-16 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.40000000e+01  1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.50000000e+01]]
[[ 1.00000000e+00  4.16176525e-16  1.50208255e-16 -1.06345632e-16
  -8.24030404e-17  1.34325308e-16]
 [ 4.16176525e-16  1.00000000e+00 -8.43326867e-17  1.95948779e-16
   2.22394574e-16  5.86930094e-17]
 [ 1.50208255e-16 -8.43326867e-17  1.00000000e+00 -1.90610578e-16
  -9.35420471e-17  3.51990850e-16]
 [-1.06345632e-16  1.95948779e-16 -1.90610578e-16  1.00000000e+00
   1.55813695e-17  9.557

### U의 직교성 깨뜨리기

In [70]:
U[0,3] = 0
print(U)

[[-3.26223352  2.81287214 -6.62441679  0.         -4.89255587 -5.63095594]
 [-6.88666459 -5.48422252  3.50002138  3.04391244 -2.41033495 -4.92114347]
 [-0.49273064  1.41800287 -3.741353    7.61676876 -8.81858287  5.68598269]
 [-4.60543239  1.24289517  2.99876048 -5.61420983 -0.42127601 10.87137039]
 [-2.32244631  8.90556527  4.70584024  3.37524042  1.12304787 -3.76456671]
 [-3.88395874  0.38267525 -6.53695138  3.8472286   9.32990186  2.0941887 ]]


In [73]:
Q,R = np.linalg.qr(U, 'complete')
print(R)
# 대각원소가 달라졌다

[[ 1.00000000e+01  2.22044605e-15 -3.55271368e-15 -2.16408475e+00
  -2.66453526e-15 -2.66453526e-15]
 [ 0.00000000e+00  1.10000000e+01  4.44089210e-15  1.69635414e+00
   8.04911693e-16 -6.66133815e-16]
 [ 0.00000000e+00  0.00000000e+00  1.20000000e+01 -3.66206140e+00
  -3.55271368e-15  8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.01991060e+01
  -3.18223982e+00 -3.66251356e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.36335377e+01 -8.54876905e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.45208533e+01]]


## 연습 문제 8-6

### M x N Orthogonal Matrix

In [100]:
m = 6
Q,R = np.linalg.qr(np.random.rand(m,m))
print(Q)

[[-0.10453245 -0.09711292 -0.87798789 -0.27039309 -0.00093748 -0.36832866]
 [-0.05285401 -0.688244    0.19792546 -0.65818664 -0.08859538  0.20807059]
 [-0.33746697 -0.2877013  -0.29884398  0.37045064  0.45124369  0.61088603]
 [-0.56993026  0.59877128  0.02058711 -0.47195681 -0.05140889  0.30140092]
 [-0.53492323 -0.23814282  0.01640587  0.36492052 -0.71798754 -0.0905698 ]
 [-0.5113043  -0.13739792  0.31616778  0.02310914  0.5199809  -0.59060434]]


### Norm

In [101]:
print(np.linalg.norm(Q, 2))

Qnorm = np.sqrt(np.sum(Q**2))/np.sqrt(m)
print(Qnorm)

1.0000000000000002
1.0


In [103]:
m=6
v = np.random.rand(m)
print(np.linalg.norm(v))
print(np.linalg.norm(Q@v))

1.3609207848472238
1.3609207848472242


## 연습 문제 8-7

### QR 분해의 R 행렬

In [105]:
Q,R = np.linalg.qr(np.random.rand(10,4), 'complete')
print(R)

[[-2.1440579  -2.18991187 -1.52847347 -1.90012832]
 [ 0.         -1.29402631 -0.27649879 -0.75537233]
 [ 0.          0.          0.91208633  0.0222274 ]
 [ 0.          0.          0.          0.92062941]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


### R의 처음 N행의 완전 역행렬 = R의 의사역행렬

In [113]:
RS = R[:4,:]

RS_inv = np.linalg.inv(RS)
print(RS_pinv)

RS_pinv = np.linalg.pinv(R)
print(RS_pinv)


[[-4.66405314e-01  7.89308937e-01 -5.42322767e-01 -3.01916702e-01]
 [-2.11326117e-16 -7.72781814e-01 -2.34268656e-01 -6.28407921e-01]
 [-6.75320197e-17 -2.74635994e-16  1.09638745e+00 -2.64708496e-02]
 [-1.88561507e-16  3.43457999e-16  1.57370596e-16  1.08621340e+00]]
[[-4.66405314e-01  7.89308937e-01 -5.42322767e-01 -3.01916702e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.11326117e-16 -7.72781814e-01 -2.34268656e-01 -6.28407921e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-6.75320197e-17 -2.74635994e-16  1.09638745e+00 -2.64708496e-02
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.88561507e-16  3.43457999e-16  1.57370596e-16  1.08621340e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
