8-1


In [ ]:
import numpy as np

Q = np.random.randn(5, 5)
Qt = Q.T
Qi = np.linalg.inv(Q)

np.allclose(Qt@Q, np.eye(5))
np.allclose(Q@Qt, np.eye(5))
np.allclose(Qi@Q, np.eye(5))
np.allclose(Q@Qi, np.eye(5))

True

8-2

In [ ]:
V = np.random.randn(4,4)
Q = np.zeros((4,4))

for i in range(4):

    Q[:,i] = V[:,i]

    a = V[:,i]
    for j in range(i):
        q = Q[:,j]
        Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q #투영성분제거 -> 직교

    Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i]) #정규화

Q2,R = np.linalg.qr(V)

Q - Q2

array([[-1.11022302e-16,  2.83052635e-01, -1.29497481e+00,
        -3.20020194e-01],
       [ 2.77555756e-17,  1.40488011e+00,  4.45603544e-01,
         1.28992757e+00],
       [ 1.11022302e-16, -7.02474886e-01,  1.34264770e+00,
        -1.06954809e-01],
       [-3.46944695e-18,  1.20528923e+00,  5.67252035e-01,
        -1.49071614e+00]])

8-3

In [ ]:
U = np.linalg.qr(np.random.randn(6,6))[0]
Q, R = np.linalg.qr(U)

np.allclose(R, np.eye(6))

True

In [ ]:
for i in range(U.shape[0]): #U.shape[0]: U 행렬의 행 수를 반환
  U[:,i] = U[:,i]*(10+i)

Q, R = np.linalg.qr(U)

diagonal = np.diag(R)
diagonal

array([10., 11., 12., 13., 14., 15.])

In [ ]:
Q_transpose = Q.T @ Q
Q_transpose

array([[ 1.00000000e+00, -1.50829176e-17,  5.94561193e-17,
        -8.57458222e-18, -3.63902649e-17, -5.78680726e-17],
       [-1.50829176e-17,  1.00000000e+00,  3.15469681e-17,
         2.46473412e-17,  2.08041131e-18, -7.26010147e-17],
       [ 5.94561193e-17,  3.15469681e-17,  1.00000000e+00,
         2.19460066e-16,  3.41619131e-17,  2.79267992e-17],
       [-8.57458222e-18,  2.46473412e-17,  2.19460066e-16,
         1.00000000e+00,  4.39317312e-18, -3.45665359e-17],
       [-3.63902649e-17,  2.08041131e-18,  3.41619131e-17,
         4.39317312e-18,  1.00000000e+00,  7.86148222e-17],
       [-5.78680726e-17, -7.26010147e-17,  2.79267992e-17,
        -3.45665359e-17,  7.86148222e-17,  1.00000000e+00]])

In [ ]:
U[0,3] = 0 #q_{1,4}

q,r = np.linalg.qr(U)
R

array([[ 1.00000000e+01, -8.88178420e-16,  4.44089210e-16,
         6.66133815e-16, -3.33066907e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.10000000e+01,  0.00000000e+00,
        -1.66533454e-16, -1.77635684e-15, -8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.20000000e+01,
        -3.55271368e-15,  2.66453526e-15, -1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.30000000e+01, -8.88178420e-16,  1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.40000000e+01, -8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.50000000e+01]])

8-6

In [ ]:
Q,R = np.linalg.qr(np.random.randn(12,12))

np.linalg.norm(Q,2)
np.sqrt(np.sum(Q**2))/np.sqrt(12)

1.0

In [ ]:
v = np.random.randn(12,1)

norm_v  = np.linalg.norm(v)
norm_Qv = np.linalg.norm(Q@v)

norm_v
norm_Qv

3.1967950595222865

8-7

In [ ]:
A = np.random.randn(10,4)

_,R = np.linalg.qr(A,'complete') #complete: R이 상삼각 형태를 유지

In [ ]:
Rsub = R[:4,:] #(4,n)의 크기를 갖는 하위행렬

Rsub_inv = np.linalg.inv(Rsub)
Rleftinv = np.linalg.pinv(R)

Rsub_inv
Rleftinv

array([[ 4.05339303e-01, -3.08927884e-01, -2.12386985e-01,
        -3.12395630e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.84870012e-16,  4.51529399e-01,  2.27372903e-01,
         3.51171277e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.55960961e-18,  5.19525136e-17, -2.86092639e-01,
        -8.25520310e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.74268306e-16, -1.09180957e-16, -1.18474337e-16,
        -4.68388623e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])