In [6]:
#4-1
A = np.arange(12).reshape(3,4)

r = 1
c = 3

sub = A[1,3]

print('The matrix element at index (' + str(r+1) + ',' + str(c+1) + ') is ' + str(sub))

The matrix element at index (2,4) is 7


In [11]:
#4-2
C = np.arange(100).reshape(10,10)
C1 = B[0:5:1, 0:5:1]
print(C)
print(C1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [13]:
#4-6
B = np.arange(10).reshape(5,2)
D = np.arange(6).reshape(2,3)

BD = np.zeros((5,3)) # (5,3) 크기의 0으로 채워진 결과 행렬 #튜플(괄호 한 번 더)로 모양 지정하기

for i in range(5): # 행렬 B의 각 행에 대해 반복
    for j in range(3): # 행렬 D의 각 열에 대해 반복
        BD[i, j] = np.dot( B[i,:],D[:,j]) # B의 i번째 행과 D의 j번째 열을 내적하여 BD[i, j]에 저장

BD2 = B@D

print(BD)
print(BD2)

[[ 3.  4.  5.]
 [ 9. 14. 19.]
 [15. 24. 33.]
 [21. 34. 47.]
 [27. 44. 61.]]
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]
 [21 34 47]
 [27 44 61]]


In [19]:
#4-8
def isMatrixSymmetric(S):
    E = S -S.T #대칭 행렬일 경우 차이는 0. 서로 동일하기 때문
    sse = np.sum(E**2) #제곱 오차 합
    return sse < 10**-15 #sse가 매우 작은 경우, 대칭 행렬로 간주

F = np.random.randn(5,5) #랜덤행렬
FtF = F.T @ F # 대칭행렬

print(isMatrixSymmetric(F))
print(isMatrixSymmetric(FtF))

False
True


In [22]:
#4-9
G = np.random.randn(4,4)
GtG = (G + G.T) / 2 #대칭행렬로 만드는 법: 행렬을 자신의 전치로 평균화

print(isMatrixSymmetric(G))
print(isMatrixSymmetric(GtG))

False
True
