In [2]:
#1-2
def normOfVect(v):
    return np.sqrt(np.sum(v**2))

In [3]:
w = np.array([1,2,3,4])
print(normOfVect(w))

5.477225575051661


In [4]:
w = np.array([1,2,3,4])
print(normOfVect(w))

5.477225575051661


In [5]:
#1-5
v = np.array([[8,7,4,5]])

In [6]:
vt = np.zeros((4,1))
#빈 배열 생성의 필요성
#(1)데이터 저장: 행 벡터를 열 벡터로 변환할 때, 변환된 값을 저장할 공간이 필요
#(2)형태 지정: 변환된 배열의 형태(행과 열의 수)를 미리 지정해주어야 함
#np.zeros를 사용하는 이유
#(1)초기화: np.zeros((4, 1))는 모든 요소가 0인 배열을 생성
#이 배열은 나중에 변환된 값을 저장할 공간으로 사용

In [7]:
for i in range(v.shape[1]):
    vt[i,0] = v[0,i]
#for i in range(v.shape[1])는 v의 열 수만큼 반복합니다. v.shape[1]은 v의 열의 개수를 반환
#vt[i,0] = v[0,i]는 v의 각 열의 값을 vt의 각 행에 할당. v의 행 벡터가 vt의 열 벡터로 변환
#vt[i,0]:vt 배열에서 열 벡터의 i번째 행을 선택
    #열 벡터 vt는 (n, 1) 형태로, i는 행 인덱스를 나타내고 0은 열 인덱스를 나타냄
#v[0, i]: v 배열에서 원래 행 벡터의 첫 번째 행의 i번째 열을
    #행 벡터 v는 (1, n) 형태로, 0은 행 인덱스를 나타내고 i는 열 인덱스

In [8]:
print(v), print(' ')
print(vt)

[[8 7 4 5]]
 
[[8.]
 [7.]
 [4.]
 [5.]]


In [9]:
#1-6
c = np.random.randn(12)
#벡터 생성: np.random.randn(12)는 평균이 0이고 표준편차가 1인 정규 분포에서 12개의 랜덤 샘플을 생성하여 벡터 c를 만듦
#이 벡터는 임의의 값으로 채워진 길이 12의 배열

In [10]:
#제곱 노름 계산 (내적 사용)
sqrNrm1 = np.dot(c,c)
#벡터 v의 제곱 노름은 ∥𝑣∥=루트(𝑣⋅𝑣)
#v⋅v는 벡터 v와 자기 자신과의 내적을 의미

In [11]:
def normOfVect(c):
    return np.sqrt(np.sum(c**2))
#제곱 노름 계산 (함수 사용)
sqrNrm2 = normOfVect(c)**2
#normOfVect(c)는 벡터 c의 노름을 계산하는 사용자 정의 함수
#이 함수는 벡터 c의 각 요소를 제곱하고 합산한 후 제곱근을 취하여 노름을 반환

In [12]:
print(sqrNrm1)
print(sqrNrm2)

6.685143499594841
6.685143499594841


In [14]:
#1-7
#벡터의 차원을 20으로 설정
n=20

In [15]:
a = np.random.randn(n,1)
b = np.random.randn(n,1)
#열벡터를 사용하는 주된 이유는 수학적 표기법과 배열 연산의 편리함 때문
#행벡터로 초기화한 벡터도 내적 계산에 사용할 수는 있음

In [16]:
#내적계산
atb = np.sum(a*b)
bta = np.sum(b*a)

In [17]:
atb-bta

0.0

In [18]:
#내적계산 2 
#내적: v^Tw
atb_dot = np.dot(a.T,b)
bta_dot = np.dot(b.T,a)

In [19]:
atb_dot-bta_dot

array([[0.]])

In [20]:
print(atb_dot)
print(atb)

[[-6.81474849]]
-6.814748492445342


In [21]:
#1-9
t = np.random.randn(5)
r = np.random.randn(5)

In [22]:
t_para = r * (np.dot(t,r)/np.dot(r,r))
t_perp = t - t_para
#1차원 배열의 경우, t_para.T와 t_para는 동일
#따라서 np.dot(t_para.T, t_perp)는 np.dot(t_para, t_perp)와 같은 결과를 생성

In [23]:
print(t)
print(t_para + t_perp)

[-0.34958889 -1.82310594  1.72463666  1.37857617 -0.80814035]
[-0.34958889 -1.82310594  1.72463666  1.37857617 -0.80814035]


In [24]:
print(np.dot(t_para, t_perp))

-1.1102230246251565e-16
