## 선형대수학 스터디
**작성자:** 구재영 \
**교재명:** 개발자를 위한 실전 선형대수학 \
**CH8 직교 행렬과 QR 분해:** 선형대수학의 핵심 분해법 1

### 연습문제 8-1

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc

%matplotlib inline

rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

np.random.seed(42)

In [2]:
# Generating random matrix Q

Q, R = np.linalg.qr(np.random.rand(3,3))

Q_T = Q.T                   # transpose
Q_inv = np.linalg.inv(Q)    # inverse

In [3]:
# Verifying the conditions

vrfy1 = np.dot(Q_T, Q)     # Q^T * Q
vrfy2 = np.dot(Q, Q_T)     # Q * Q^T
vrfy3 = np.dot(Q_inv, Q)   # Q^(-1) * Q
vrfy4 = np.dot(Q, Q_inv)   # Q * Q^(-1)

In [4]:
print(np.allclose(vrfy1, np.eye(3)),
      np.allclose(vrfy2, np.eye(3)),
      np.allclose(vrfy3, np.eye(3)),
      np.allclose(vrfy4, np.eye(3)))

True True True True


### 연습문제 8-2

In [5]:
# Generate a random matrix
A = np.random.rand(4,4)

# Perform QR decomposition to get Q and R
Q1, R1 = np.linalg.qr(np.random.rand(4,4))

In [6]:
# Implement Gram-Schmidt manually to generate the Q matrix

def gs_4by4(A):
    
    Q = np.zeros((4,4))
    
    for j in range(4):
        v = A[:, j]
        for i in range(j):
            v = v - np.dot(Q[:, i], A[:, j]) * Q[:, i]
        Q[:, j] = v / np.linalg.norm(v)
    
    return Q

In [7]:
# Apply Gram-Schmidt to matrix A
Q_gs = gs_4by4(A)

# Compare the results from Gram-Schmidt and np.linalg.qr()
np.allclose(Q1, Q_gs)

False

In [8]:
import numpy as np

# Generate a random matrix A
A = np.random.rand(4, 4)

# Perform QR decomposition to get Q and R from the same matrix A
Q1, R1 = np.linalg.qr(A)

# Implement Gram-Schmidt manually to generate the Q matrix
def gs_4by4(A):
    Q = np.zeros((4, 4))
    
    for j in range(4):
        v = A[:, j]
        for i in range(j):
            v = v - np.dot(Q[:, i], A[:, j]) * Q[:, i]
        Q[:, j] = v / np.linalg.norm(v)
    
    return Q

# Compare the absolute values of the matrices
np.allclose(np.abs(Q1), np.abs(gs_4by4(A)))

True

근데 `np.abs()` 씌워야만 np.allclose()의 결과가 `True`로 출력되는데 괜찮은 게 맞는지... (괜찮을 것 같기는 한데...)

### 연습문제 8-3

**STEP 01:** Orthogonal matrix U & QR decomposition

In [9]:
# 6*6 random matrix
U = np.linalg.qr(np.random.randn(6,6))[0]

In [10]:
# (Just to check...)

# Are the result of QR decomposition of U & U generated by np.linalg.qr the same?
U1, R1 = np.linalg.qr(U)

# Yeap
np.allclose(U, U1)

True

In [11]:
np.allclose(R1, np.eye(6))

True

**STEP 02:** Reset the norm of each column of U & QR decomposition

In [12]:
# Handle the norm of each column vecs
for i in range(6):
    U[:,i] = U[:,i] / np.linalg.norm(U[:, i]) * (10 + i)

In [13]:
# QR decomposition revisited
U2, R2 = np.linalg.qr(U)

np.allclose(np.diag(R2), [10, 11, 12, 13, 14, 15])

True

**STEP 03:** Break the orthogonality of U

In [14]:
# Let's just set U_{1,4} to be 0
U[0, 3] = 0

# QR decomposition re-re-visited
Q_broken, R_broken = np.linalg.qr(U)

Q_broken

array([[-0.45883536,  0.65459238,  0.40509179,  0.09661792, -0.43203991,
         0.02976677],
       [-0.5140669 , -0.2207295 ,  0.38268418, -0.59117719,  0.43642108,
        -0.02475279],
       [-0.0941992 ,  0.28359542, -0.53406382, -0.4242598 , -0.1112497 ,
        -0.6581057 ],
       [ 0.536422  ,  0.60928005,  0.11692028, -0.32854271,  0.40572547,
         0.23410562],
       [ 0.44241062, -0.26566343,  0.41954258, -0.44165285, -0.58700954,
        -0.13432187],
       [-0.18126256, -0.02370025, -0.46318784, -0.39771922, -0.31828966,
         0.70181929]])

In [15]:
np.round(R_broken,3)

array([[ 1.0000e+01, -0.0000e+00,  0.0000e+00,  7.0800e-01,  0.0000e+00,
        -0.0000e+00],
       [ 0.0000e+00,  1.1000e+01, -0.0000e+00, -1.0110e+00,  0.0000e+00,
         0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  1.2000e+01, -6.2500e-01,  0.0000e+00,
        -0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.2834e+01,  7.1800e-01,
        -5.3000e-02],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.3982e+01,
         3.0000e-03],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         1.5000e+01]])

In [16]:
np.round(R2, 3)

array([[10., -0.,  0.,  0.,  0., -0.],
       [ 0., 11., -0.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0., -0.],
       [ 0.,  0.,  0., 13., -0.,  0.],
       [ 0.,  0.,  0.,  0., 14., -0.],
       [ 0.,  0.,  0.,  0.,  0., 15.]])

- We can see that the diagonal elements are set to be the same (mostly), but the off-diagonal entries have changed to have non-zero values
- Umm... Maybe just because the orthogonality is no more satisfied...
    - if the orthogonality is not the thing anymore,
    - then the inner product of column vectors will not be 0,
    - and maybe it is reflected on the off-diagonal entries of `R_broken`

### 연습문제 8-6

**STEP 01:** Orthogonal matrix & its norm

In [17]:
# random M*N matrix
A = np.random.randn(5, 3)

# QR decomposition to generate orthogonal matrix Q
Q, R = np.linalg.qr(A)

In [18]:
# induced 2-norm
max_singular_value = np.linalg.norm(Q, ord=2)

# Frobenius norm
frobenius_norm = np.linalg.norm(Q, ord='fro') / np.sqrt(5)

np.isclose(max_singular_value, 1), np.isclose(frobenius_norm, 1)

(True, False)

False...? Let's check the case of square matrix

In [19]:
# random M*N matrix
A = np.random.randn(3,3)

# QR decomposition to generate orthogonal matrix Q
Q, R = np.linalg.qr(A)

In [20]:
# induced 2-norm
max_singular_value = np.linalg.norm(Q, ord=2)

# Frobenius norm
frobenius_norm = np.linalg.norm(Q, ord='fro') / np.sqrt(3)

np.isclose(max_singular_value, 1), np.isclose(frobenius_norm, 1)

(True, True)

True only for the square matrix...

**STEP 02:** The norm of $v$ & $Q_v$

In [21]:
# a random vector
v = np.random.randn(3,1)

# norms
n_v  = np.linalg.norm(v)
n_Qv = np.linalg.norm(Q@v)

np.round(n_v, 3) == np.round(n_Qv, 3)

True

### 연습문제 8-7

In [22]:
# Generate a random matrix
A = np.random.randn(10,4)

# get R
Q,R = np.linalg.qr(A,'complete')

# examine R
np.round(R,3)

array([[-2.943, -0.661, -0.045,  0.502],
       [ 0.   , -1.782, -0.327,  0.399],
       [ 0.   ,  0.   ,  2.844,  0.568],
       [ 0.   ,  0.   ,  0.   , -2.652],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ]])

In [23]:
r = np.linalg.inv(R[:4,:])

r_inv = np.linalg.inv(r)
r_leftinv = np.linalg.pinv(r)

r_inv

array([[-2.94311366, -0.66051702, -0.04509821,  0.50192797],
       [-0.        , -1.78212698, -0.32666019,  0.3986718 ],
       [ 0.        ,  0.        ,  2.84414059,  0.5683825 ],
       [-0.        , -0.        , -0.        , -2.65227614]])

In [24]:
r_leftinv

array([[-2.94311366e+00, -6.60517017e-01, -4.50982123e-02,
         5.01927972e-01],
       [ 1.96292628e-16, -1.78212698e+00, -3.26660193e-01,
         3.98671801e-01],
       [-8.87592227e-16, -1.81524724e-16,  2.84414059e+00,
         5.68382497e-01],
       [ 2.63138469e-16,  5.64453550e-16,  2.03157875e-16,
        -2.65227614e+00]])

In [25]:
np.allclose(r_inv, r_leftinv)

True