## 선형대수학 스터디
**작성자:** 구재영 \
**교재명:** 개발자를 위한 실전 선형대수학 \
**CH4 행렬, 파트 1:** 행렬과 행렬의 기본 연산

### 연습문제 4-1
이 연습 문제를 통해 행렬 원소의 인덱싱에 익숙해질 수 있습니다. np.arange(12). reshape (3,4)를 사용해 3x4 행렬을 생성합니다. 그런 다음 파이썬 코드를 작성해 두 번째 행, 네 번째 열의 원소를 추출합니다. 다른 행과 열 인덱스를 선택할 수 있도록 소프트 코딩 하고 다음과 같은 메시지를 출력해 봅니다. \
`The matrix element at index (2,4) is 7.`

In [1]:
import numpy as np

In [2]:
A = np.arange(12).reshape(3,4)

print(f'The matrix element at index (2,4) is {A[1,3]}')

The matrix element at index (2,4) is 7


### 연습문제 4-2
이 문제와 다음 문제는 행렬을 잘라서 부분 행렬을 얻는 내용입니다. 먼저 [그림 4-6]의 왼 쪽 행렬 C를 만들고 파이썬의 슬라이싱을 사용해 처음 5개의 행과 5개의 열로 이루어진 하 위 행렬을 추출합니다. 이 행렬을 C, 이라고 부릅니다. [그림 4-6]을 재현해 보는데 만약 파이썬 시각화 코딩이 어렵다면 부분 행렬을 올바르게 추출하는 데에만 초점을 맞추세요.

In [3]:
# Matrix C
C = np.arange(100).reshape((10,10))
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
# Submatrix
C_1 = C[0:5,0:5]
C_1

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

### 연습문제 4-3

In [5]:
# Submatrices
C_2 = C[5:10, 0:5]
C_3 = C[0:5, 5:10]
C_4 = C[5:10, 5:10]

# Reshape
C_remat = np.block([
    [C_4, C_2],
    [C_3, C_1]
])
C_remat

array([[55, 56, 57, 58, 59, 50, 51, 52, 53, 54],
       [65, 66, 67, 68, 69, 60, 61, 62, 63, 64],
       [75, 76, 77, 78, 79, 70, 71, 72, 73, 74],
       [85, 86, 87, 88, 89, 80, 81, 82, 83, 84],
       [95, 96, 97, 98, 99, 90, 91, 92, 93, 94],
       [ 5,  6,  7,  8,  9,  0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19, 10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29, 20, 21, 22, 23, 24],
       [35, 36, 37, 38, 39, 30, 31, 32, 33, 34],
       [45, 46, 47, 48, 49, 40, 41, 42, 43, 44]])

### 연습문제 4-6
for 루프를 사용해 행렬 곱셈을 코딩합니다. 그후 NumPy @ 연산자를 사용해 결과를 비교합니다.\
이 연습 문제는 행렬 곱셈에 대한 이해를 강화하는 데 도움이 되지만 데이터 과학 분야에서는 이중으로 루프를 쓰는 대신 를 사용하는 것이 좋습니다

In [6]:
# Generate two matrices to use in matrix multiplications

A = np.random.randn(3,3)
B = np.random.randn(3,3)

In [7]:
# Initialize
C = np.zeros((3,3))

# for loop for matrix products (multiplications)
for re in range(3):
    for ce in range(3):
        C[re,ce] = np.dot(A[re,:], B[:,ce])
        
C

array([[-3.4838711 , -3.97740621, -0.55064616],
       [-1.923402  , -2.49992349, -0.23598772],
       [-0.18440046, -0.53157407, -0.0253924 ]])

In [8]:
A @ B == C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

We can see with the naked eyes that the `for` loop and `@` returns the same result.

### 연습문제 4-8
이 문제에서 여러분은 행렬의 대칭 여부를 확인하는 파이썬 함수를 작성합니다. 행렬을 입력으로 받고 그 행렬이 대칭이면 True, 행렬이 비대칭이면 False 불리언을 출력해야 합니다. 작은 크기의 컴퓨팅 반올림이나 정밀도 오류로 인해 동일한 행렬이 그렇지 않다고 나올 수 있다는 것을 명심하세요. \
따라서 적절한 허용 오차를 사용하여 동일성을 테스트해야 합니다. 대칭 행렬과 비대칭 행렬에 대해서 함수를 테스트해 보세요.

In [9]:
# Function to check if the matrix is symmetric

def isSym(A):
    
    # First check if the input matrix is square matrix
    if np.shape(A)[0] == np.shape(A)[1]:
        D = A - A.T
        SSE = np.sum(D**2)
        return SSE < 10**-15
    
    else:
        print(f"{A} cannot be a symmetric matrix. Only square matrices can be symmetric.")

In [10]:
print(A)
print(isSym(A))

[[ 0.12529839  0.70939323  1.91514102]
 [-0.66564047  0.54076622  0.77297286]
 [-0.52354601  0.19487743 -0.09390915]]
False


In [11]:
V = [[1,2],
    [2,1]]
V = np.array(V)

isSym(V)

True

In [12]:
V2 = [[1,2,3],
     [1,2,3]]
V2 = np.array(V2)

isSym(V2)

[[1 2 3]
 [1 2 3]] cannot be a symmetric matrix. Only square matrices can be symmetric.


### 연습문제 4-9
앞서 비대칭 사각 행렬로부터 대칭 행렬을 만드는 덧셈 방법이 있다고 언급했습니다. 방 법은 매우 간단합니다. 행렬을 자신의 전치로 평균화합니다. 파이썬에서 이 알고리즘을 구현하고 결과가 실제로 대칭인지 확인합니다(힌트: 이전 연습 문제에서 작성한 함수를 사용해 보세요).

In [13]:
A, isSym(A)

(array([[ 0.12529839,  0.70939323,  1.91514102],
        [-0.66564047,  0.54076622,  0.77297286],
        [-0.52354601,  0.19487743, -0.09390915]]),
 False)

We checked that A is an asymmetric matrix, so we are going to get the answer using predefined matrix A.

In [14]:
tfA = (A + A.T) / 2
tfA, isSym(tfA)

(array([[ 0.12529839,  0.02187638,  0.6957975 ],
        [ 0.02187638,  0.54076622,  0.48392514],
        [ 0.6957975 ,  0.48392514, -0.09390915]]),
 True)