# (2주차) Ch4 행렬, part 1 : 행렬과 행렬의 기본 연산

## Ch4.1 Numpy에서 행렬 생성과 시각화

### Ch4.1.1 행렬 시각화와 인덱싱, 슬라이싱

In [ ]:
# 하나의 큰 행렬에서 행 2~4와 열 1~5의 부분 행렬을 추출하는 예제
A = np.arange(60).reshape(6,10)
sub = A[1:4:1, 0:5:1]

In [ ]:
# 원본 행렬
[[ 0 1 2 3 4 5 6 7 8 9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 41 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
# 부분 행렬
[[ 10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]

### Ch4.1.2 특수 행렬

In [ ]:
# Numpy 난수 행렬
Mrows = 4 # shape 0
Ncols = 6 # shape 1
A = np.random. randn(Mrows, Ncols)

## Ch4.2 행렬 수학 : 덧셈, 스칼라 곱셈, 아다마르곱

### Ch4.2.1 덧셈과 뺄셈

### Ch4.2.2 행렬 '이동'

In [ ]:
# 수치 예제
A = np.array([ [4,5,1],[0,1,11],[4,9,7] ])
s = 6
A + s # 이동 X
A + s*np.eye(len(A)) # 이동 O

### Ch4.2.3 스칼라 곱셈과 아다마르곱

In [ ]:
A = np.random.randn(3,4)
B = np.random.randn(3,4)

A*B # 아다마르곱 O
np.multiply(A,B) # 아다마르곱 O
A@B # 아다마르곱 X (행렬곱)

## Ch4.3 표준 행렬 곱셈

### Ch4.3.1 행렬 곱셈 유효성에 관한 규칙

### Ch4.3.2 행렬 곱셈

### Ch4.3.3 행렬-벡터 곱셈

In [ ]:
# 기하학적 변환
M = np.array([ [2,3], [2,1] ])
x = np. array([ [1,1.5] ]).T
Mx = M#x

## Ch4.4 행렬 연산 : 전치

In [ ]:
# 2차원 Numpy 배열에 대해 전치하는 방법
A = np.array([ [3,4,5],[1,2,3] ])
A_T1 = A.T # 메서드
A_T2 = np.transpose(A) # 함수

### Ch4.4.1 내적과 외적 표기법

## Ch4.5 행렬 연산 : LIVE EVIL(연산 순서)

## Ch4.6 대칭 행렬

### Ch4.6.1 비대칭 행렬로부터 대칭 행렬 생성하기

## Ch4.7 정리



*   행렬 : 숫자의 표
  *   행렬의 응용 : 행렬을 열벡터 집합, 행벡터 집합, 개별값의 배열로 개념화
  *   행렬을 시각화하면 insight 도출 굳, 가독성 굳
*   특수 행렬에는 여러 범주 존재
  *   행렬 유형에 따른 특성을 숙지하면 행렬식과 응용 분야를 이해하는데 도움됨
*   산술 연산은 원소별로 동작함
  *   산술 연산 : 행렬의 덧셈, 스칼라 곱셈, 아다마르곱
*   행렬의 '이동' : 대각 원소에 상수를 더하는 것 (대각이 아닌 요소는 변경 X)
  *   이동의 응용 : 고윳값 찾기, 통계 모델의 정규화 같은 머신러닝
*   행렬 곱셈 : 왼쪽 행렬의 행들과 오른쪽 행렬의 열들 사이의 내적
  *   곱셈 행렬은 행-열 쌍 간의 매핑으로 이루어진 집합
  *   행렬 곱셈 유효성의 규칙
      > *(MxN)(NxK) = (MxK)*
*   LIVE EVIL 여러 행렬의 곱의 전치 : 각 행렬을 전치하고 역순으로 곱한 것
*   대칭 행렬 : 대각을 거울로 보고 반사된 형태
  *   각 행 = 대응되는 열
  *   A = A^T로 정의
  *   모든 행렬에 자신의 전치 행렬을 곱하면 대칭 행렬임
      *   결과 행렬인 A(^T)A : 통계 모델과 특잇값 분해의 핵심






# Ch4 연습문제

**[연습문제 4-1]**

np.arange(12).reshape(3,4)를 사용해 3*4 행렬을 생성하여라.

그 다음에 python 코드를 작성하여 두번째 행, 네번째 열의 원소를 추출하여라.

다른 행과 열 인덱스를 선택할 수 있도록 소프트 코딩하여 아래와 같은 메시지를 출력하게 하여라.

> The matrix element at index (2,4) is 7.


In [5]:
import numpy as np

# 3x4 행렬 생성
matrix = np.arange(12).reshape(3, 4)

# 소프트 코딩: 추출할 행, 열 설정
row = 1  # 두 번째 행
col = 3  # 네 번째 열

# 행렬의 특정 요소 추출
element = matrix[row, col]

# 출력, 1씩 더해주삼
print(f"The matrix element at index ({row+1},{col+1}) is {element}.")

The matrix element at index (2,4) is 7.


**[연습문제 4-2]**

행렬을 잘라서 부분 행렬을  얻는 문제이다.

[그림4-6]의 왼쪽 행렬 C를 만들고 python의 슬라이싱을 사용하여 처음 5개의 행과 5개의 열로 이루어진 하위 행렬(이하 C1)을 추출하여라.

(단, 시각화가 어려울 시 부분 행렬만 올바르게 출력할 것.)

In [8]:
import numpy as np

# 10x10 행렬 생성
C = np.arange(100).reshape((10, 10))

# 슬라이싱으로 하위 행렬 추출
C_1 = C[:5, :5]

# 원본 행렬과 부분 행렬 출력
print("원본 행렬 : \n", C)
print("\n하위 행렬 : \n", C_1)

# 시각화 못하겠티비

원본 행렬 : 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

하위 행렬 : 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


**[연습문제 4-6]**

for 루프를 사용해 행렬 곱셈을 코딩하여라.

그 다음에 Numpy @ 연산자를 사용해 결과를 비교하여라.

(데이터과학 분야에서는 이중으로 루프를 쓰는 대신 @를 사용하는 것이 좋다.)

In [10]:
import numpy as np

# 두 개의 행렬 생성
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# A (2x3)와 B (3x2)의 행렬 곱을 계산하기 위한 결과 행렬 초기화 (2x2 크기)
result = np.zeros((A.shape[0], B.shape[1]))

# for 루프를 이용한 행렬 곱셈 구현
for i in range(A.shape[0]):  # A의 행 개수
    for j in range(B.shape[1]):  # B의 열 개수
        for k in range(A.shape[1]):  # A의 열 개수 == B의 행 개수
            result[i, j] += A[i, k] * B[k, j]

# Numpy @ 연산자를 사용한 행렬 곱셈
result_numpy = A @ B

# 결과 출력
print("for 루프 결과 : \n", result)
print("Numpy @ 결과 : \n", result_numpy)


for 루프 결과 : 
 [[ 58.  64.]
 [139. 154.]]
Numpy @ 결과 : 
 [[ 58  64]
 [139 154]]


**[연습문제 4-8]**

행렬의 대칭 여부를 확인하는 파이썬 함수를 작성하여라.

행렬을 입력으로 받고 그 행렬이 대칭이면 True, 비대칭이면 False 불리언을 반환하도록 하여라.

(작은 크기의 컴퓨팅 반올림이나 정밀도 오류로 인해 '동일한' 행렬임에도 그렇지 않다고 나올 수 있으므로, 적절한 허용 오차를 사용하여라.)



In [15]:
import numpy as np

# 행렬의 대칭 여부를 확인하는 함수
def is_symmetric(matrix, tol=1e-8): # 1e-8은 0.00000001의 작은 값으로 보편적인 허용 오차로 많이 사용
    # 전치 행렬과 원래 행렬이 같은지 확인 (허용 오차 범위 내에서)
    return np.allclose(matrix, matrix.T, atol=tol)

# 행렬, 걍 여기다 입력
matrix = np.array([[1, 2, 3],
                             [2, 5, 6],
                             [3, 6, 9]])

# 결과 출력
print("대칭 행렬 여부 : ", is_symmetric(matrix))

대칭 행렬 여부 :  True


**[연습문제4-9]**

비대칭 사각 행렬로부터 대칭 행렬을 만드는 덧셈 방법을 이용하는 문제이다.

행렬을 자신의 전치로 평균화하는 알고리즘을 python 구현하고, 실제 결과가 대칭인지 확인하여라.

(이전 연습문제의 함수를 이용할 것.)

In [16]:
# 비대칭 사각 행렬 생성
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 행렬과 그 전치 행렬의 평균을 구하여 대칭 행렬 생성
A_sym = (A + A.T) / 2

# 결과 출력
print("비대칭 행렬 : \n", A)
print("\n대칭 행렬 : \n", A_sym)

# 대칭 여부 확인
print("\n대칭 행렬 여부 확인:", is_symmetric(A_sym))

비대칭 행렬 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

대칭 행렬 : 
 [[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]

대칭 행렬 여부 확인: True
