In [1]:
import numpy as np

#### [연습문제 8-1]

- 난수 행렬 Q 생성하고 Q^T와 Q^-1을 계산하는 코드를 작성해서 이를 구현.
- 그런 다음 네 식이 모두 단위 행렬이 되는 것을 보여주기.(Q^TQ, QQ^T, Q^-1Q, QQ^-1)

In [5]:
A = np.random.randn(4,4)
Q, R = np.linalg.qr(A)
QT = Q.T
Qinv = np.linalg.inv(Q)

m1 = QT @ Q
m2 = Q @ QT
m3 = Qinv @ Q
m4 = Q @ Qinv

print(m1)
print(m2)
print(m3)
print(m4)

[[ 1.00000000e+00 -1.37274479e-16 -2.23042137e-17  6.60914111e-17]
 [-1.37274479e-16  1.00000000e+00 -1.69070935e-16 -8.07921956e-17]
 [-2.23042137e-17 -1.69070935e-16  1.00000000e+00  1.47166693e-17]
 [ 6.60914111e-17 -8.07921956e-17  1.47166693e-17  1.00000000e+00]]
[[ 1.00000000e+00 -2.07507728e-16 -1.03316604e-16  1.29335942e-16]
 [-2.07507728e-16  1.00000000e+00 -3.07615964e-17  3.96254876e-18]
 [-1.03316604e-16 -3.07615964e-17  1.00000000e+00  1.74018115e-17]
 [ 1.29335942e-16  3.96254876e-18  1.74018115e-17  1.00000000e+00]]
[[ 1.00000000e+00 -3.17745675e-17 -3.60500992e-17  4.41992195e-17]
 [-4.09178725e-17  1.00000000e+00  4.46736343e-18  1.92840111e-17]
 [ 5.45136187e-18 -2.33541634e-17  1.00000000e+00  9.79833962e-17]
 [-3.75980434e-17  7.32440680e-17  8.06031858e-17  1.00000000e+00]]
[[ 1.00000000e+00 -1.21089346e-17  5.48617075e-18  1.94234036e-17]
 [-2.12992852e-17  1.00000000e+00  3.28301416e-17 -7.77446170e-20]
 [-6.47529235e-17  4.40313951e-17  1.00000000e+00 -7.433865

#### [연습문제 8-2]

- 그람-슈미트 과정 구현 (4x4 난수 행렬 사용). 결과를 np.linalg.qr의 Q와 대조하여 확인

In [23]:
V = np.random.randn(4,4)
Q,R = np.linalg.qr(V)

x1 = V[:,0]
x2 = V[:,1]
x3 = V[:,2]
x4 = V[:,3]

v1 = x1
v2 = x2 - (x2@v1)/(v1@v1)*v1
v3 = x3 - (x3@v1)/(v1@v1)*v1 - (x3@v2)/(v2@v2)*v2
v4 = x4 - (x4@v1)/(v1@v1)*v1 - (x4@v2)/(v2@v2)*v2 - (x4@v3)/(v3@v3)*v3

# 단위 길이로 정규화
vv1 = v1/np.linalg.norm(v1)
vv2 = v2/np.linalg.norm(v2)
vv3 = v3/np.linalg.norm(v3)
vv4 = v4/np.linalg.norm(v4)

# 행렬화
Q2 = np.column_stack((vv1,vv2,vv3,vv4))

print(Q)
print(Q2)
print(Q-Q2)



[[-0.55252969 -0.18563036 -0.20098242 -0.78731085]
 [ 0.15430928 -0.97610125  0.12352244  0.09031722]
 [-0.22080808 -0.10881013 -0.8803904   0.40536019]
 [-0.78876066 -0.0304643   0.41141343  0.45570554]]
[[-0.55252969 -0.18563036  0.20098242  0.78731085]
 [ 0.15430928 -0.97610125 -0.12352244 -0.09031722]
 [-0.22080808 -0.10881013  0.8803904  -0.40536019]
 [-0.78876066 -0.0304643  -0.41141343 -0.45570554]]
[[-1.11022302e-16 -5.55111512e-17 -4.01964842e-01 -1.57462171e+00]
 [ 2.77555756e-17  1.11022302e-16  2.47044878e-01  1.80634435e-01]
 [ 0.00000000e+00 -1.38777878e-17 -1.76078081e+00  8.10720385e-01]
 [-1.11022302e-16 -1.04083409e-17  8.22826865e-01  9.11411072e-01]]


#### [연습문제 8-3]

- 6x6 난수 행렬의 QR 분해로부터 U라는 직교 행렬을 만든다.
- U의 QR 분해를 계산하고 R=I임을 확인한다.
- U의 각 열의 노롬을 수정한다.
- 1~6열의 노름을 10,11,...,15값의 노름으로 설정한다.
- 변조된 U 행렬을 QR 분해하여 그 R의 대각선 원소가 10에서 15인 대각 행렬인지 확인
- 이 행렬의 Q^TQ는?
- 원소 u(1,4)=0으로 설정하여 U의 직교성을 깨뜨리면 R은 어떻게 되며 그 이유는?

In [39]:
M = np.random.randn(6,6)
U,R = np.linalg.qr(M)
UQ,UR = np.linalg.qr(U)
print(np.round(UR,3)) # UR = I

print("-----------------------------")
# U의 1열 norm 10으로 수정
for i in range(6):
  U[:,i] = (i+10)*U[:,i]

UQ,UR = np.linalg.qr(U)
# UR의 대각선 원소가 10에서 15인 대각 행렬인지 확인
print(np.round(UR,3)) # 맞음!

print("-----------------------------")

U[0][3] = 0
UQ,UR = np.linalg.qr(U)
print(np.round(UR,3))

[[ 1.  0.  0. -0. -0. -0.]
 [ 0.  1. -0.  0.  0. -0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1. -0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
-----------------------------
[[10.  0.  0. -0. -0.  0.]
 [ 0. 11. -0.  0. -0. -0.]
 [ 0.  0. 12.  0.  0. -0.]
 [ 0.  0.  0. 13.  0.  0.]
 [ 0.  0.  0.  0. 14.  0.]
 [ 0.  0.  0.  0.  0. 15.]]
-----------------------------
[[10.     0.     0.    -1.522 -0.     0.   ]
 [ 0.    11.    -0.     2.993 -0.    -0.   ]
 [ 0.     0.    12.     4.858  0.    -0.   ]
 [ 0.     0.     0.     6.903 -1.62   5.631]
 [ 0.     0.     0.     0.    13.906  0.656]
 [ 0.     0.     0.     0.     0.    13.887]]


#### [연습문제 8-6]

- 난수 행렬의 QR 분해를 통해 MxN 직교 행렬을 만든다.
- np.linalg.norm을 사용하여 유도된 2-노름을 계산하고 5장에서 배운 방정식을 사용하여 M의 제곱근으로 나누어 프로베니우스 노름을 계산한다.
- 두 값이 모두 1인지 확인한다.
- 무작위로 M개의 원소를 가진 열벡터 v를 생성한 다음 v와 Qv의 노름을 계산한다. 이 노름은 서로 같아야 한다.

In [109]:
M = np.random.randint(1,10)
N = 3

A = np.random.randn(M,N)
Q,R = np.linalg.qr(A, mode='complete')

print(np.linalg.norm(Q,2))
print(np.sqrt(np.trace(Q.T @ Q)) / np.sqrt(M))

v = np.random.randn(M)


print(np.linalg.norm(v,2))
print(np.linalg.norm(Q@v,2))

1.0000000000000002
1.0
3.286011252285586
3.2860112522855864


#### [연습문제 8-7]

- A가 높고 최대열계수일 때, R의 처음 N행은 상삼각이고, 반면에 N+1부터 M까지의 행은 0이다.
- 파이썬에서 10x4 난수 행렬을 사용하여 이를 확인
- 경제형(축소) 분해가 아닌 완전형(전체) QR 분해를 사용해야 한다.
- (1) 처음 N개의 행을 구성하는 행렬의 역행렬 구하기
- (2) 의사역행렬 구하기
- R의 처음 N행의 완전 역행렬이 의사역행렬의 처음 N열과 같다는 것을 확인

In [113]:
A = np.random.randn(10,4)

Q,R = np.linalg.qr(A, mode='complete')
print(np.round(R,3))

[[-2.889  1.214  0.196 -2.418]
 [ 0.    -2.652 -0.812  0.028]
 [ 0.     0.     3.195 -1.087]
 [ 0.     0.     0.     2.396]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]]


In [115]:
M1 = np.linalg.inv(R[:4,:])
M2 = np.linalg.pinv(R)

print(np.round(M1,3))
print(np.round(M2,3))


[[-0.346 -0.159 -0.019 -0.356]
 [-0.    -0.377 -0.096 -0.039]
 [ 0.     0.     0.313  0.142]
 [ 0.     0.     0.     0.417]]
[[-0.346 -0.159 -0.019 -0.356  0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.377 -0.096 -0.039  0.     0.     0.     0.     0.     0.   ]
 [-0.    -0.     0.313  0.142  0.     0.     0.     0.     0.     0.   ]
 [-0.     0.     0.     0.417  0.     0.     0.     0.     0.     0.   ]]
