In [1]:
import numpy as np

#### [연습문제 1-2]

- normOfVector를 계산하는 알고리즘 작성.
- 작성한 알고리즘이 np.linalg.norm() 이랑 결과가 같은지 확인해보자!

In [3]:
def normOfVector(v):
  return np.sum(v**2)**0.5

v1 = np.array([1, 2, 3])
print(normOfVector(v1))
print(np.linalg.norm(v1))

v2 = np.array([1, 1, 1])
print(normOfVector(v2))
print(np.linalg.norm(v2))

3.7416573867739413
3.7416573867739413
1.7320508075688772
1.7320508075688772


#### [연습문제 1-5]

- np.transpose(v) 또는 v.T와 같은 내장 함수 또는 메서드를 사용하지 않고 형벡터를 열벡터로 전치하는 for 루프 작성

In [9]:
v = np.array([1, 2, 3, 4, 5])

# transpose할 빈 vector 생성
tv = np.zeros((len(v), 1))

# transpose
for i in range(len(v)):
  tv[i] = v[i]

print(tv)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


#### [연습문제 1-6]

- squared norm of a vector를 벡터 자체의 내적으로 계산할 수 있다.

In [11]:
# squared norm of a vector
v = np.array([1,2,3])
snv = np.sum(v**2)

# 벡터 내적
pv = np.dot(v, v)

print(snv)
print(pv)

14
14


#### [연습문제 1-7]

- 내적의 교환 법칙을 입증하는 코드 작성

In [21]:
a = np.random.randn(3,1)
b = np.random.randn(3,1)

print(a)
print(b)

atb = np.dot(a.T, b)
bta = np.dot(b.T, a)

print(atb,bta)

[[-0.36519729]
 [-0.68993643]
 [ 0.74427999]]
[[-1.13402984]
 [ 1.03771153]
 [ 0.93255823]]
[[0.39227406]] [[0.39227406]]


#### [연습문제 1-9]

- 직교벡터 분해 구현
- 두 난수 벡터 t와 r로 시작해서 [그림 1-8] 재현하기
- 그 다음 두 성분의 합이 t이고 tㅗr과 t||r이 직교하는지 확인

In [23]:
t = np.array([0.8, -0.8])
r = np.array([1.2, -0.1])

t_para = r * (np.dot(t, r) / np.dot(r, r))
t_perp = t - t_para

print(t)
print(t_para+t_perp)

print(np.dot(t_para, t_perp))

[ 0.8 -0.8]
[ 0.8 -0.8]
-6.604813142437741e-17
