In [6]:
import numpy as np
import scipy.linalg

### [연습문제 9-3]

In [8]:
M = np.random.randn(4,4)

# LU 분해
P, L, U = scipy.linalg.lu(M)

print(P)
print(L)
print(U)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
[[ 1.          0.          0.          0.        ]
 [ 0.17041554  1.          0.          0.        ]
 [-0.28537224 -0.78499985  1.          0.        ]
 [ 0.01865656  0.44619239 -0.55434979  1.        ]]
[[-2.45723346 -0.39892112 -0.38121366  1.50839303]
 [ 0.          0.85579498  1.26512609  0.83479468]
 [ 0.          0.          2.25628691 -0.57705351]
 [ 0.          0.          0.         -1.15392313]]


In [9]:
np.linalg.det(M)

-5.475040780080689

In [10]:
np.linalg.det(U)

5.475040780080689

In [12]:
# 치환 행렬의 행렬식 사용(PtA = LU)
np.linalg.det(P.T @ L @ U)

-5.475040780080689

### [연습문제 9-4]
- 4x4 난수 행렬에 대해 scipy.linalg.lu을 호출한 결과를 사용해 세 번째 방정식을 직접 구현해 보기.
- AA^-1는 단위 행렬인가요?
- 수학 규칙이 아닌 SciPy의 규칙을 따르도록 코드를 수정해 보기.

In [41]:
A = np.random.randn(4,4)

# LU 분해
P, L, U = scipy.linalg.lu(A)

# A = P^T L U
print(A)
print(P.T @ L @ U)

[[-0.24843063 -0.74012666  0.21139219  0.40829915]
 [-0.56033044  0.65912208 -1.87947959 -0.55881761]
 [-0.0144326   0.01616725 -0.30700909  1.55847984]
 [ 1.41346997  0.07035363  1.04448264  0.33202611]]
[[-0.0144326   0.01616725 -0.30700909  1.55847984]
 [ 1.41346997  0.07035363  1.04448264  0.33202611]
 [-0.24843063 -0.74012666  0.21139219  0.40829915]
 [-0.56033044  0.65912208 -1.87947959 -0.55881761]]


In [42]:
# A^-1 = (P^T L U)^-1 = U^-1 L^-1 P
print(np.linalg.inv(A))
print(np.linalg.inv(U) @ np.linalg.inv(L) @ P)
A_inv = np.linalg.inv(U) @ np.linalg.inv(L) @ P

[[ 0.76978859  0.74732399 -0.17599067  1.13723494]
 [-1.93586124 -0.60525341  0.41285101 -0.57596599]
 [-0.86577362 -0.91731741  0.00777577 -0.51573315]
 [-0.14334017 -0.16750532  0.63727008 -0.08508915]]
[[-0.17599067  1.13723494  0.76978859  0.74732399]
 [ 0.41285101 -0.57596599 -1.93586124 -0.60525341]
 [ 0.00777577 -0.51573315 -0.86577362 -0.91731741]
 [ 0.63727008 -0.08508915 -0.14334017 -0.16750532]]


In [43]:
# A A_inv가 단위 행렬인가?
print(A @ A_inv)

[[-6.32582063e-17 -7.11804213e-18  1.00000000e+00  2.45432165e-17]
 [ 8.35955062e-17 -5.32382344e-17 -2.83280615e-16  1.00000000e+00]
 [ 1.00000000e+00 -7.59006337e-18  3.85355365e-17 -1.23399848e-17]
 [-1.40913278e-17  1.00000000e+00 -3.35881287e-17  4.52655221e-17]]


- 3트만에 단위 행렬 아닌 경우 발견!

In [48]:
# SciPy 규칙을 사용해봅시다.
A2 = P @ L @ U
A2_inv = np.linalg.inv(U) @ np.linalg.inv(L) @ np.linalg.inv(P)

print(A2 @ A2_inv)


[[ 1.00000000e+00  2.45432165e-17 -7.74705509e-18 -7.11804213e-18]
 [-2.83280615e-16  1.00000000e+00  8.35955062e-17 -5.32382344e-17]
 [-1.69756147e-17 -1.23399848e-17  1.00000000e+00 -3.53456390e-17]
 [-3.35881287e-17  4.52655221e-17 -1.40913278e-17  1.00000000e+00]]


### [연습문제 9-5]
- 행렬 A = PLU에서, 치환 행렬을 사용하지 않고도 A^TA를 U^TL^TLU로 계산할 수 있습니다.
- 치환 행렬을 삭제할 수 있는 이유는 무엇인가요?
- 질문에 답한 다음 파이썬에서 무작위 행렬을 사용해 P != I 일 때도 A^TA = U^TL^TLU임을 확인해 보세요.

#### 치환 행렬을 삭제할 수 있는 이유
- A^TA가 이미 대칭 행렬이기 때문에 그런 거 아닐까요..?

In [49]:
A = np.random.randn(4,4)
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)


[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [-0.49096217  1.          0.          0.        ]
 [-0.99666968  0.64900567  1.          0.        ]
 [-0.25887394 -0.2679439   0.380692    1.        ]]
[[ 1.73492914 -1.15603248  2.09286654 -1.05884862]
 [ 0.         -2.01207106  1.07258654 -0.26682582]
 [ 0.          0.          1.86745203 -2.58502042]
 [ 0.          0.          0.         -1.85882452]]


In [50]:
AtA = A.T @ A
UtLtLU = U.T @ L.T @ L @ U

print(AtA)
print(UtLtLU)

[[ 6.92719613 -0.8860665   2.81973556  2.01358125]
 [-0.8860665   4.14950775 -2.65706898 -0.97349332]
 [ 2.81973556 -2.65706898  4.62427512 -2.72270837]
 [ 2.01358125 -0.97349332 -2.72270837 10.32154812]]
[[ 6.92719613 -0.8860665   2.81973556  2.01358125]
 [-0.8860665   4.14950775 -2.65706898 -0.97349332]
 [ 2.81973556 -2.65706898  4.62427512 -2.72270837]
 [ 2.01358125 -0.97349332 -2.72270837 10.32154812]]


- P != I 일 때도 A^TA = U^TL^TLU 이다.