In [1]:
import numpy as np

### 연습 문제 8-1

In [6]:
m=np.random.randn(25).reshape(5,5)

In [19]:
I=np.eye(5,5)

In [8]:
Q,R=np.linalg.qr(m)

In [18]:
Qi=np.linalg.inv(Q)

In [24]:
np.array_equal(np.round(Q.T@Q,15),I)

True

In [25]:
np.array_equal(np.round(Q@Q.T,15),I)

True

In [26]:
np.array_equal(np.round(Qi@Q),I)

True

In [27]:
np.array_equal(np.round(Q@Qi),I)

True

### 연습 문제 8-2

In [50]:
def orthogonalize(v1, v2):
    projection = np.dot(v2, v1) / np.dot(v1, v1) * v1
    v2_orthogonal = v2 - projection
    return v2_orthogonal

In [51]:
def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm

In [65]:
A=np.random.randn(16).reshape(4,4)

In [66]:
Q1=A.copy()

In [67]:
for i in range(4):
    for j in range(i):
        Q1[:,i]=orthogonalize(Q1[:,j],Q1[:,i])
    Q1[:,i]=normalize(Q1[:,i])

In [68]:
Q2,R=np.linalg.qr(A)

In [72]:
np.round(Q1@Q1.T,3)

array([[ 1., -0.,  0., -0.],
       [-0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [-0., -0., -0.,  1.]])

In [71]:
np.round(Q2@Q2.T,3)

array([[ 1., -0., -0., -0.],
       [-0.,  1., -0., -0.],
       [-0., -0.,  1.,  0.],
       [-0., -0.,  0.,  1.]])

### 연습 문제 8-3

In [74]:
A=np.random.randn(36).reshape(6,6)

In [76]:
Q,R=np.linalg.qr(A)

In [77]:
U=Q.copy()

In [78]:
Q,R=np.linalg.qr(U)

In [82]:
np.array_equal(np.round(R,15), np.round(np.eye(6,6),15))

True

In [83]:
def normalize(v,i):
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm*15

In [87]:
for i in range(6):
    U[:,i]=normalize(U[:,i],i+10)

In [88]:
Q,R=np.linalg.qr(U)

In [94]:
np.round(R,3)

array([[15.,  0., -0., -0., -0.,  0.],
       [ 0., 15.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 15., -0.,  0.,  0.],
       [ 0.,  0.,  0., 15., -0.,  0.],
       [ 0.,  0.,  0.,  0., 15., -0.],
       [ 0.,  0.,  0.,  0.,  0., 15.]])

In [93]:
np.round(Q.T@Q,3)

array([[ 1.,  0., -0.,  0., -0.,  0.],
       [ 0.,  1., -0.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0., -0., -0.],
       [ 0.,  0.,  0.,  1., -0.,  0.],
       [-0.,  0., -0., -0.,  1., -0.],
       [ 0.,  0., -0.,  0., -0.,  1.]])

In [95]:
U[1,4]=0

In [96]:
Q,R=np.linalg.qr(U)

In [98]:
np.round(R,3)

array([[15.   ,  0.   , -0.   , -0.   , -0.495,  0.   ],
       [ 0.   , 15.   ,  0.   ,  0.   ,  0.503,  0.   ],
       [ 0.   ,  0.   , 15.   , -0.   ,  0.026,  0.   ],
       [ 0.   ,  0.   ,  0.   , 15.   , -1.302,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   , 14.82 , -0.98 ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   , 14.968]])

### 연습 문제 8-6

In [141]:
A=np.random.randn(4,4)

In [155]:
Q,R=np.linalg.qr(A)

In [156]:
Q

array([[-0.6058158 , -0.21698419, -0.67921096, -0.35295545],
       [ 0.16273116, -0.72112288,  0.3756654 , -0.55890595],
       [ 0.71628901,  0.24149162, -0.49099899, -0.43304946],
       [ 0.30567276, -0.6120306 , -0.39556031,  0.61279258]])

In [157]:
np.linalg.norm(Q,2)

1.0

In [158]:
np.sqrt(np.sum(Q**2))/np.sqrt(4) 

1.0

In [159]:
v=np.random.randn(4).reshape(-1,1)

In [160]:
v

array([[ 0.38118265],
       [-0.50939517],
       [ 0.84116475],
       [-1.02122601]])

In [161]:
np.linalg.norm(v)

1.4680750516717764

In [162]:
Qv = np.linalg.norm(Q@v)

In [163]:
np.linalg.norm(Qv)

1.4680750516717767

### 연습 문제 8-7

In [164]:
A=np.random.randn(10,4)

In [165]:
Q,R=np.linalg.qr(A,'complete')

In [167]:
np.round(R,3)

array([[ 2.454,  0.947,  0.048, -0.589],
       [ 0.   , -3.379,  0.196,  0.092],
       [ 0.   ,  0.   ,  4.123, -0.525],
       [ 0.   ,  0.   ,  0.   ,  1.473],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ]])

In [170]:
Rn=R[:4,:]

In [176]:
np.round(np.linalg.inv(Rn),1)

array([[ 0.4,  0.1, -0. ,  0.2],
       [-0. , -0.3,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0.1],
       [ 0. ,  0. ,  0. ,  0.7]])

In [175]:
np.round(np.linalg.pinv(R),1)

array([[ 0.4,  0.1, -0. ,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-0. , -0.3,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0. ,  0.2,  0.1,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -0. ,  0.7,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])