### 연습 문제 9-3

In [30]:
import numpy as np
import scipy.linalg

In [28]:
A=np.random.random((4,4))

In [40]:
P, L, U=scipy.linalg.lu(A)

In [41]:
A_det=np.linalg.det(A)

In [42]:
A_det

-0.03822062520804537

In [43]:
mul=1
for i in range(len(U)):
    mul*=U[i][i]

In [44]:
mul

0.038220625208045346

In [46]:
np.linalg.det(P)*mul

-0.038220625208045346

### 연습 문제 9-4

In [66]:
A=np.random.random((4,4))
P, L, U=scipy.linalg.lu(A)

In [67]:
np.linalg.inv(A)

array([[ 0.39764143, -0.45015021,  1.00801143, -0.05100263],
       [-0.46293434,  1.26621325,  0.34198525, -1.99629524],
       [-1.61006498,  0.0299093 , -0.17195342,  3.93888683],
       [ 2.13938195, -0.07914204, -1.12095917, -1.10161171]])

In [68]:
np.linalg.inv(U)@np.linalg.inv(L)@P.T

array([[ 0.39764143, -0.45015021,  1.00801143, -0.05100263],
       [-0.46293434,  1.26621325,  0.34198525, -1.99629524],
       [-1.61006498,  0.0299093 , -0.17195342,  3.93888683],
       [ 2.13938195, -0.07914204, -1.12095917, -1.10161171]])

### 연습 문제 9-5

In [69]:
A=np.random.random((5,5))
P,L,U=scipy.linalg.lu(A)

In [70]:
A.T@A

array([[2.05844848, 1.5595505 , 0.73941521, 1.19040945, 1.39628995],
       [1.5595505 , 1.92960411, 1.19082843, 1.2777413 , 1.4669761 ],
       [0.73941521, 1.19082843, 1.47833895, 1.29391037, 1.2190789 ],
       [1.19040945, 1.2777413 , 1.29391037, 1.32651562, 1.34919235],
       [1.39628995, 1.4669761 , 1.2190789 , 1.34919235, 1.61511263]])

In [71]:
U.T@L.T@L@U

array([[2.05844848, 1.5595505 , 0.73941521, 1.19040945, 1.39628995],
       [1.5595505 , 1.92960411, 1.19082843, 1.2777413 , 1.4669761 ],
       [0.73941521, 1.19082843, 1.47833895, 1.29391037, 1.2190789 ],
       [1.19040945, 1.2777413 , 1.29391037, 1.32651562, 1.34919235],
       [1.39628995, 1.4669761 , 1.2190789 , 1.34919235, 1.61511263]])

In [72]:
P

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [73]:
U.T@L.T@P.T@P@L@U 

array([[2.05844848, 1.5595505 , 0.73941521, 1.19040945, 1.39628995],
       [1.5595505 , 1.92960411, 1.19082843, 1.2777413 , 1.4669761 ],
       [0.73941521, 1.19082843, 1.47833895, 1.29391037, 1.2190789 ],
       [1.19040945, 1.2777413 , 1.29391037, 1.32651562, 1.34919235],
       [1.39628995, 1.4669761 , 1.2190789 , 1.34919235, 1.61511263]])

In [74]:
P.T@P## 단위행렬이 되기 때문에 영향이 없으므로 생략해도 된다.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])