### 연습 문제 13-1

In [1]:
import numpy as np

A = np.random.randn(5,5)
A = A.T@A

evals,evecs = np.linalg.eig(A)
U,s,Vt = np.linalg.svd(A)

In [8]:
print("특잇값과 고윳값")
print("고윳값:", evals)
print("특잇값:", s)

특잇값과 고윳값
고윳값: [9.22625995 0.3981225  1.457307   4.40120706 4.59083221]
특잇값: [9.22625995 4.59083221 4.40120706 1.457307   0.3981225 ]


In [13]:
print("특이 벡터와 고유벡터")
print("U:", U)
print("V:", Vt.T)
print("evecs:", evecs)

특이 벡터와 고유벡터
U: [[-0.42950136  0.39819164 -0.42348775 -0.51776015 -0.45777128]
 [-0.0797505  -0.36651    -0.55920972  0.61043752 -0.41708608]
 [ 0.16685674  0.60243421  0.41998333  0.42523553 -0.50201652]
 [-0.25904919  0.54545084 -0.34909331  0.38625602  0.60358682]
 [-0.84511584 -0.21603297  0.45791973  0.17108909 -0.01212533]]
V: [[-0.42950136  0.39819164 -0.42348775 -0.51776015 -0.45777128]
 [-0.0797505  -0.36651    -0.55920972  0.61043752 -0.41708608]
 [ 0.16685674  0.60243421  0.41998333  0.42523553 -0.50201652]
 [-0.25904919  0.54545084 -0.34909331  0.38625602  0.60358682]
 [-0.84511584 -0.21603297  0.45791973  0.17108909 -0.01212533]]
evecs: [[ 0.42950136  0.45777128  0.51776015  0.42348775  0.39819164]
 [ 0.0797505   0.41708608 -0.61043752  0.55920972 -0.36651   ]
 [-0.16685674  0.50201652 -0.42523553 -0.41998333  0.60243421]
 [ 0.25904919 -0.60358682 -0.38625602  0.34909331  0.54545084]
 [ 0.84511584  0.01212533 -0.17108909 -0.45791973 -0.21603297]]


In [15]:
A = np.random.randn(5,5)
A = A.T+A

evals,evecs = np.linalg.eig(A)
U,s,Vt = np.linalg.svd(A)

In [16]:
print("특잇값과 고윳값")
print("고윳값:", evals)
print("특잇값:", s)
print()
print("특이 벡터와 고유벡터")
print("U:", U)
print("V:", Vt.T)
print("evecs:", evecs)

특잇값과 고윳값
고윳값: [ 5.77862576  3.01711032 -4.33230928 -2.25773801  0.51544122]
특잇값: [5.77862576 4.33230928 3.01711032 2.25773801 0.51544122]

특이 벡터와 고유벡터
U: [[-0.29766006 -0.4532524  -0.7914043  -0.27458002  0.06515982]
 [-0.47645189 -0.55642361  0.31366156  0.43031491 -0.42406587]
 [-0.39117399 -0.09476354  0.22328921  0.14476522  0.87589254]
 [ 0.6439221  -0.68960847  0.22402388 -0.16205066  0.18264001]
 [-0.34167136 -0.02037303  0.41862978 -0.8319961  -0.12400492]]
V: [[-0.29766006  0.4532524  -0.7914043   0.27458002  0.06515982]
 [-0.47645189  0.55642361  0.31366156 -0.43031491 -0.42406587]
 [-0.39117399  0.09476354  0.22328921 -0.14476522  0.87589254]
 [ 0.6439221   0.68960847  0.22402388  0.16205066  0.18264001]
 [-0.34167136  0.02037303  0.41862978  0.8319961  -0.12400492]]
evecs: [[ 0.29766006 -0.7914043  -0.4532524  -0.27458002 -0.06515982]
 [ 0.47645189  0.31366156 -0.55642361  0.43031491  0.42406587]
 [ 0.39117399  0.22328921 -0.09476354  0.14476522 -0.87589254]
 [-0.6439221   

### 연습 문제 13-2

In [18]:
# The proof that |Uw|=|w| comes from expanding the vector magnitude to the dot product:
# |Uw|^2 = (Uw)'(Uw) = w'U'U'w = w'Iw = w'w = |w|^2
# 무슨말일까
U,s,Vt = np.linalg.svd(np.random.randn(5,5))
w = np.random.randn(5,1)

print( np.linalg.norm(U@w) )
print( np.linalg.norm(  w) )

1.466467532707103
1.4664675327071026


In [19]:
U

array([[ 0.90717562, -0.07747501,  0.27751653, -0.26563132,  0.15314893],
       [ 0.11310966, -0.89902239, -0.22742975,  0.31984704, -0.1579194 ],
       [-0.11772113, -0.0515804 ,  0.8135152 ,  0.54774762,  0.14712838],
       [ 0.34744328,  0.37943473, -0.43901594,  0.71628893,  0.17177782],
       [ 0.17223095,  0.19780071,  0.12929929,  0.11849298, -0.94892175]])

In [20]:
w

array([[ 0.59664072],
       [-0.44529204],
       [-0.10055192],
       [-1.21486969],
       [ 0.33202833]])

In [21]:
U@w

array([[ 0.92140932],
       [ 0.04967565],
       [-0.74566058],
       [-0.73067917],
       [-0.45734282]])

### 연습 문제 13-7

In [23]:
A = np.random.randn(6,4)

Linv = np.linalg.inv(A.T@A)@A.T

Apinv = np.linalg.pinv(A)

print(np.round( Linv - Apinv ,5))

[[-0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -0. -0.]
 [ 0. -0.  0.  0.  0.  0.]
 [-0.  0.  0.  0. -0.  0.]]


In [24]:
A = np.random.randn(4,6)

Rinv = A.T@np.linalg.inv(A@A.T)

Apinv = np.linalg.pinv(A)

print(np.round( Rinv - Apinv ,5))

[[-0.  0.  0. -0.]
 [ 0. -0.  0. -0.]
 [ 0. -0.  0.  0.]
 [-0. -0. -0.  0.]
 [ 0. -0. -0. -0.]
 [ 0. -0. -0.  0.]]
